-- =====================================================================
-- V1__baseline_and_geospatial.sql
-- Full schema baseline + geospatial foundation for Food-Fiesta.
-- Flyway is the sole schema authority (Hibernate runs in validate mode).
-- Requires the postgis/postgis image (PostGIS >= 3.x). SRID 4326 (WGS84).
-- =====================================================================

-- 0. PostGIS ------------------------------------------------------------
CREATE EXTENSION IF NOT EXISTS postgis;

-- 1. Users --------------------------------------------------------------
CREATE TABLE customer_info (
    u_id       INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uname      VARCHAR(255),
    uemail     VARCHAR(255),
    upassword  VARCHAR(255),
    unumber    BIGINT
);

-- 2. Admins -------------------------------------------------------------
CREATE TABLE admin (
    admin_id       INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    admin_name     VARCHAR(255) NOT NULL,
    admin_email    VARCHAR(255) NOT NULL,
    admin_password VARCHAR(255),
    admin_number   VARCHAR(255)
);

-- 3. Restaurants (new geospatial aggregate root) ------------------------
CREATE TABLE restaurant (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name             VARCHAR(150) NOT NULL,
    address          VARCHAR(255),
    avg_prep_minutes INTEGER      NOT NULL DEFAULT 20,   -- feeds AI ETA
    is_active        BOOLEAN      NOT NULL DEFAULT TRUE,
    location         geometry(Point, 4326) NOT NULL,     -- POINT(lon lat)
    created_at       TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at       TIMESTAMPTZ  NOT NULL DEFAULT now()
);
CREATE INDEX idx_restaurant_location ON restaurant USING GIST (location);

-- 4. Drivers ------------------------------------------------------------
-- Postgres holds the durable last-known snapshot; Redis Geo holds the
-- hot, high-frequency live position.
CREATE TABLE driver (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name             VARCHAR(150) NOT NULL,
    phone            VARCHAR(20),
    status           VARCHAR(20)  NOT NULL DEFAULT 'OFFLINE'
        CHECK (status IN ('OFFLINE','AVAILABLE','ASSIGNED','DELIVERING')),
    last_location    geometry(Point, 4326),
    last_location_at TIMESTAMPTZ,
    created_at       TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at       TIMESTAMPTZ  NOT NULL DEFAULT now()
);
CREATE INDEX idx_driver_last_location ON driver USING GIST (last_location);
CREATE INDEX idx_driver_available ON driver (status) WHERE status = 'AVAILABLE';

-- 5. Products (menu items owned by a restaurant) ------------------------
CREATE TABLE product_table (
    pid           INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pname         VARCHAR(255),
    pprice        DOUBLE PRECISION,
    pdescription  VARCHAR(255),
    restaurant_id BIGINT REFERENCES restaurant (id)
);
CREATE INDEX idx_product_restaurant ON product_table (restaurant_id);

-- 6. Orders (with lifecycle + tracking columns) -------------------------
CREATE TABLE order_info (
    o_id              INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    o_name            VARCHAR(255),
    o_price           DOUBLE PRECISION,
    o_quantity        INTEGER,
    order_date        TIMESTAMP,
    total_ammout      DOUBLE PRECISION,
    user_u_id         INTEGER REFERENCES customer_info (u_id),
    restaurant_id     BIGINT REFERENCES restaurant (id),
    driver_id         BIGINT REFERENCES driver (id),
    status            VARCHAR(20) NOT NULL DEFAULT 'PLACED'
        CHECK (status IN ('PLACED','CONFIRMED','PREPARING','OUT_FOR_DELIVERY','DELIVERED','CANCELLED')),
    delivery_location geometry(Point, 4326),
    estimated_eta_at  TIMESTAMPTZ
);
CREATE INDEX idx_order_delivery_location ON order_info USING GIST (delivery_location);
CREATE INDEX idx_order_status ON order_info (status);
